### ISSUE TITLE
rounded borders after 2022.11.01 ?

### ISSUE THREAD

**Issue by ChristophCaina** [frenck/home-assistant-theme-outline#42]
# Problem/Motivation
After the installation of HA 2022.11.01 I've noticed an update of "Outline", too - so I've installed it.
But after outline was updated, I could not see any difference between the original theme and Outline anymore.

Here's how your "before" and "after" comparrission looks:
![grafik](https://user-images.githubusercontent.com/26391061/199663044-4793819c-f108-40ce-b565-5793f7b80b8b.png)

![grafik](https://user-images.githubusercontent.com/26391061/199663061-3d6b9513-9251-4c8c-8c09-7f8a4bdcca97.png)

And here, how's my System looks like:

1. Default Theme (Homeassistant standard)
![grafik](https://user-images.githubusercontent.com/26391061/199663240-8389874f-f24a-4ff5-9455-b394233f1a8d.png)

2. Outline
![grafik](https://user-images.githubusercontent.com/26391061/199663286-a7935543-16b3-4635-87b2-a46cba2e5db9.png)

3. Google (Light) (checking, if skins are working at all)
![grafik](https://user-images.githubusercontent.com/26391061/199663428-9edd32dc-2870-424b-9dcb-6e399f3ad637.png)

4. "Clear" (confirming themes are working)
![grafik](https://user-images.githubusercontent.com/26391061/199663472-0794ad67-e65b-4359-83b6-f561b28bc3da.png)

## Expected behavior

I really liked the clear look from "outline" with the edged cards...
I don't really see, why it has changed / or isn't working anymore - since the theme was updated right after the update to 2022.11.01

## Actual behavior

See, Problem / Motivation

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The only thing the theme did, was remove the shadow of the borders and outline them instead.

This is now part of the default theme since Home Assistant 2022.11.0, so this theme doesn't change anything anymore (its sole purpose is now default behavior).

Therefore I've shipped an update to get out the deprecation message:

<https://github.com/frenck/home-assistant-theme-outline/releases/tag/v3.0.0>

The theme will be removed from the HACS store in a month or 2 ish.

../Frenck
